name: Labb_DE24_Needs//test/build/deploy

on:
  workflow_dispatch:
    inputs:
      user_name:
        description: "Ange om pytest skallköras ja/nej. Om nej så utförs inte testet och applikationen byggs ej"

jobs:
 ja:
    if: ${{ github.event.inputs.user_name == 'ja' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install pytest
        run: pip install pytest
      - name: Run pytest
        run: pytest -q

 build:
    needs: ja
    runs-on: ubuntu-latest
    steps:
      - name: Build
        run: echo "Bygger applikationen..."

 deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: deploy
        run: echo "Deployar applikationen"

 nej:
   if: always()
   runs-on: ubuntu-latest
   steps:
     - name: terminate
       run: echo "Programmet avslutas"


 

 

      
    




  

   




